# Use the aspnet runtime image for 
FROM mcr.microsoft.com/dotnet/aspnet:7.0-focal-arm64v8 AS final
WORKDIR /app

# Copy the published output from the build container
COPY . .

# Set the entry point for the application
ENTRYPOINT ["dotnet", "BlogKjellCoppin.dll"]
