name: Build and Deploy

on:
  push:
    branches:
      - AddRunner
jobs:
  build_and_run:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: make build image
        run: docker build -t build_image -f BlogKjellCoppin/Dockerfile_build BlogKjellCoppin

      - name: run build container
        run: docker run --rm -v $(pwd):/app -w /app build_image

      - name: make run image 
        run: docker build -t run_image -f BlogKjellCoppin/Dockerfile_run publish

        
       
      

