on:
  push:
    branches:
      - AddRunner
jobs:
  build_and_run:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
       
      - name: Change directory to application folder
        run: cd BlogKjellCoppin

      - name: check
        run: ls

