on:
  push:
    branches:
      - AddRunner
jobs:
  build_and_run:
    name: build and run
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       
       - name: check env
         run: ls 

       - name: check machine
         run: whoami
